Fixes validation error
pydantic.error_wrappers.ValidationError: 1 validation error for InstrumentSchema
cusip
    field required (type=value_error.missing)